problem:
  name: 'DamBreak'
  template_case: '3DdamBreak'
  parameters:
    meshType:
      type: choice
      values: ["pMesh", "cartesianMesh", "tetMesh"]
      value_type: str
      is_ordered: True
    refineInterval:
      type: range
      value_type: int
      bounds: [50, 500]
      log_scale: False
    refinementLevel:
      type: range
      value_type: int
      bounds: [1, 2]
      log_scale: False
    numberOfProcessors:
      type: range
      value_type: int
      bounds: [8, 12]
      log_scale: False
    LBThreshold:
      type: range
      value_type: float
      bounds: [0.05, 0.95]
      log_scale: False
  objectives:
    Pressure:
      command: ['python3', 'computeRMSPressure.py', '1']
      threshold: 1e3
      minimize: True
      lower_is_better: True
    WaterHeight:
      command: ['python3', 'computeRMSWaterHeight.py', '4']
      threshold: 1e-3
      minimize: True
      lower_is_better: True
    ExecutionTime:
      command: ['awk', '/^ExecutionTime =/{v=$3} END{print v}', 'log.interFoam']
      threshold: 40
      minimize: True
      lower_is_better: True

meta:
  case_subdirs_to_clone: ["0.orig", "dynamicCode", "pressure_experiment.csv", "height_experiment.csv",
    "computeRMSPressure.py", "computeRMSWaterHeight.py", "geometry"]
  clone_destination: ""
  case_run_mode: local
  metric_value_mode: local
  case_run_command: ['./Allrun']
  #case_run_command: ['sbatch', '-J', '$CASE_NAME', './Allrun.slurm', '$CASE_PATH']
  slurm_status_query: ['sacct', '--name', '$CASE_NAME', '-o', 'JobName%60,State', '-n']
  n_trials: 5
  n_parallel_trials: 2
  use_saasbo: True
  n_pareto_points: 4
  #file_copies:
  #  refinementType:
  #    template: "/constant/dynamicMeshDict"
  # Parameters can also be substituted per-file
  scopes:
    "/system/meshDict":
      meshType: "mesher"
    "/constant/dynamicMeshDict":
      refineInterval: "refineInterval"
      refinementLevel: "maxRefinement"
      LBThreshold: "allowableImbalance"
    "/system/decomposeParDict":
      numberOfProcessors: "numberOfSubdomains"
